RELEVANT_KEYWORDS = set([
    "immigration",
    "immigrant",
    "u.s",
    "united states",
    "policy",
    "reform",
    "migrants",
    "diversity",
    "border",
    "refugees",
    "visa",
    "green card",
    "uscis",
    "dhs",
    "department of homeland security",
    "deport",
    "asylum",
    "foreign"
])
